### ISSUE TITLE
Browse by month rather than day

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#101]
Currently with directory browsing you can only view the articles published on a given day at once.
Since it is rare to publish multiple articles on one day, this is rather cumbersome. So I propose to replace this:

    URL/YYYY/MM/DD/ID

with:

    URL/YYYY/MM/DD-ID
    
This enables one to browse by month, in order.

**Comment by novoid** [comment]
Sorry, with my lazyblorg homepage being online for maybe a decade, it's simply too late for me to change things like that.

However, since #35 is still open, this might help here as well.
