### ISSUE TITLE
Unable to escape formatting

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#111]
I have a text that contains the word `C++` two times over multiple lines, resulting in an unintended strikethrough.

First of all, formatting specifiers should not be interpreted beyond lines - they are not in org-mode, either.

Then if I put a non-breaking space before the plus sign as recommended in https://orgmode.org/manual/Escape-Character.html, the plus vanishes in the final output.

Full article here, issue is at the bottom: https://barelybuggy.blog/2024/08/16/rust-reflection/

**Comment by novoid** [comment]
> I have a text that contains the word `C++` two times over multiple lines, resulting in an unintended strikethrough.

I see.

> First of all, formatting specifiers should not be interpreted beyond lines - they are not in org-mode, either.

That's not true. Formatting specifiers are working properly in Emacs Org-mode as long there is not more than one line break in between. 

> Then if I put a non-breaking space before the plus sign as recommended in https://orgmode.org/manual/Escape-Character.html, the plus vanishes in the final output.

So we do have a workaround 1.

> Full article here, issue is at the bottom: https://barelybuggy.blog/2024/08/16/rust-reflection/

Workaround 2 would be to insert more line breaks in between.

Sorry, I know that the parser is somewhat difficult in this respect. If you find a better way that doesn't break formatting elsewhere, let me know. Until then, we both will have to use workarounds.
