### ISSUE TITLE
discuss: Variablizing and Separating Content from Config

### ISSUE THREAD

**Issue by nickgarber** [novoid/lazyblorg#15]
I have a few ideas on how to make lazyblorg easier to use and would like to know your thoughts.

1. Allow config variables to be set using environment variables.
2. Be more forgiving with configuration options, so that (if desired) warnings are produced but a site render will still succeed.
3. Support multiple sites from a single lazyblorg install through use of named configuration sets.

My hope with these proposals is to support the continued growth of the lazyblorg community, and to make it easier to accept contributions back into upstream.

I'm cooking/prototyping these ideas in a fork but ideally would like to submit PRs upstream to you.

Would you be receptive to these changes? Let's discuss!

**Comment by novoid** [comment]
Hi Nick,

Thanks for your thoughts!

I do think that I'd like to evaluate (and merge?) them separately.

Config variables as env vars: what is the advantage over different config.py files? IMO config settings are pretty stable after initial set-up.

Produce result despite of warnings: I'm okay with ignoring warnings that do not result in broken links or anything that might produce errors for the user of the blog. And as far as I remember, this was in my head when I decided to abort the blog render process. Can you give me examples where warnings (not errors) do not lead to a result? 

Multiple sites: how about a switch to define the config.py file? I'd think of this method first if I'd have this use-case (which I don't have so far).

**Comment by nickgarber** [comment]
I'm using environment variables to override the values in the `config.py` - but it's all really just an initial steps toward the goal of moving individual site configs outside of the lazyblorg repo.

If that becomes possible it'll mean that site config could be stored apart from the repo, which would allow everyone to track the upstream lazyblorg repo for changes and improvements.

What I've done so far is based around pulling from the environment for some existing variables as well as adding a few.

**Variablizing Configuration and Operations**
_*New variables:*_
- `_timestamp`: 
  - an rfc3339/minute -like timestamp
- `_propertyname`: 
  - the name of the config set
  - the name used for cache data
  - uses 'default' if not specified.
- `_instance`: 
  - the name used for log and export
  - uses `_propertyname + '.' + _timestamp` if not specified.
- `lazyblorg__uri_app_dir`: 
  - path to the lazyblorg install/clone
  - searches `$PATH` for `lazyblorg.py` if not specified.
- `lazyblorg__uri_template_dir`:
  - a location with template files, such as template.org and CSS files
  - uses `${HOME}/.vault/docs/forms/_include/lazyblorg.${_propertyname}` (I'm happy to adjust to consensus default values for any of these paths)
  - if the required template is included among the content files, this variable isn't needed
  - it's only included to make it easier to separate the publish content from the publish config
- `lazyblorg__uri_export_dir`:
  - the parent directory for all lazyblorg site exports
  - the site is exported to `$lazyblorg__uri_export_dir + '/' + $_instance`
- `lazyblorg__uri_cache_dir`:
  - the parent directory where cache data, such as tag metadata, is stored
  - the cache location used is `$lazyblorg__uri_cache_dir + '/' + $_propertyname`
- `lazyblorg__uri_content_dirs`:
  - the dirs to search for '*.org' files
  - use the `$PWD` if not specified.
- `lazyblorg__uri_content_files`:
  - a list of org-mode files for lazyblorg to parse for content

_*For Setting Existing Variables from the Environment:*_
- The prefix 'lazyblorg__' is used as a namespace for environment variables.
- The variable names are lower-cased and appended to the prefix, such that `lazyblorg__image_cache_directory` corresponds to the `config.py` variable called `IMAGE_CACHE_DIRECTORY`.



**Workflows**

The above may seem like a lot of info, but it all only exists to support the following workflows.

_*Casual Interest*_
- clone/install lazyblorg
- add to PATH
- cd to content dir
- run `lazyblorg .`
  - a few of the most important variables used are shown in INI format in the output
  - show a short blurb about how to change and persist configuration
  - the export path is included in the output


_*Exploratory Use / Single Property*_
- starting with the 'Casual Interest' workflow
- copy and paste the presented config to file `${HOME}/.config/lazyblorg/default.ini`
- now when running `lazyblorg`, (regardless of $PATH or $PWD), the same content is rendered to a blog, because the value 'default' is used if no other value is specified
- the user is now free to manipulate the config settings of this file to experiment with different content and publish options


_*Default Config with Local Overrides*_
- starting with the 'Exploratory Use' workflow
- the user wishes to publish a new set or subset of content
- the user adds a `.lazyblorg.ini` file to the root of the content
- in this config file, a `parent_propertyname` variable may optionally be set, if set the values from the correspondingly named config is imported first, then the values in the `.lazyblorg.ini` is merged on top, overriding any existing variables.


_*Multi-Property*_
- starting with the 'Exploratory Use' workflow
- the user has realized that lazyblorg is the way to go for publishing various content "properties"
- the user copies the default.ini file to new files called projectA.ini and projectB.ini and edits those relevant configs, (in this case content path and export path variables), for each
- the user is now able to export to each, with distinct config, by running `lazyblorg -p projectA`, or `lazyblorg -p projectB` as desired


_*Parent Properties as Treatments*_
- starting with the 'Default Config with Local Overrides' or 'Multi-Property' workflow
- the user has realized the property configs can be used as "treatments" for multiple properties
- the user establishes preset visual styles as top-level properties and wants to compare treatments for an existing property
- the user goes to the content directory, where the `.lazyblorg.ini` file may or may not already include a `parent_propertyname` value
- the user invokes lazyblorg with environment variable overrides in order to view the results
  - (ex.) `env lazyblorg__parent_propertyname=spooky lazyblorg .` 
  - (ex.) `env lazyblorg__parent_propertyname=professional lazyblorg .` 
  - (ex.) `env lazyblorg__parent_propertyname=zany lazyblorg .` 


Notes for the above workflows:
- I'm really open to feedback on all of this. For example, I think some of the variable or concept names should be made more clear.
- any persistent variables may be set/overridden by an environment variable.
- ideally, other config data formats in addition to INI would be supported, such as YAML (perhaps with http://yaml.readthedocs.io/en/latest/index.html)


My first steps are simple and exploratory but I'd like to see the lazyblorg community and use-cases expand. It's a good choice for me and I believe also for many others though a few might need some help to realize it.


Wow, didn't expect to write so much!

Warm regards,
Nick

**Comment by nickgarber** [comment]
Now to actually answer your questions!

_**Config variables as env vars: what is the advantage over different config.py files?**
IMO config settings are pretty stable after initial set-up._

- The environment variables would allow easy access to supplement/override values in the `config.py`, but I'm not thinking it would replace it.
- I think of the `config.py` still as the config engine and the variable values themselves as the config data.
- If the config data can be stored separately it could be saved, (perhaps in git), alongside the content.
- If the `config.py` is kept clear of the specific values, then it can evolve independently of the data.
- The example I have in mind is https://github.com/novoid/lazyblorg/compare/master...yqrashawn:master . There is some interesting and appealing adaptation by @yqrashawn, but it's a fork that isn't so straightforward to merge. It looks like some portion of the changes are for personalization and publish control, which could be handled with config variable overrides and environment variables are just one way to handle that. Another portion of the changes are for styling, if it were possible to variablize the way this is handled, maybe it would make styles easier to share?
- Speaking to the question more directly, on yqrashawn's fork there are changes to detect a DEV_MODE environment variable to change certain behavior. This is an example of where the config changes slightly based on the context it's viewed, even when the content basically stays the same.



_Produce result despite of warnings: I'm okay with ignoring warnings that do not result in broken links or anything that might produce errors for the user of the blog. And as far as I remember, this was in my head when I decided to abort the blog render process. **Can you give me examples where warnings (not errors) do not lead to a result?**_
- I'm thinking that perhaps another CLI flag like `--ignore-broken-links` could be added, (analogous to `--ignore-missing-ids`).
- This comes up when testing using Org-Mode content from https://github.com/novoid/lazyblorg/tree/master/testdata. I mostly want to see what my content looks like alongside the testdata content, so I dont mind if the image links are broken, but the site wont render I dont get a change to view anything.



_Multiple sites: **how about a switch to define the config.py file?** I'd think of this method first if I'd have this use-case (which I don't have so far)._
- This would be a nice feature!
- I'd like to see this added in addition to the other changes I mentioned, but I dont mind if it arrives first. The other changes will take longer and need more review anyway. As long as you'd still be willing to discuss and consider them I'm content for the work to land when/as it's ready.


Thanks!

**Comment by novoid** [comment]
Sorry for not responding so far.

`--ignore-broken-links` should be easy to implement. I'll probably do this.

Many other suggestions by you are reasonable requests I totally understand. However, now I do get a psychological issue because those requests do not match my personal use-cases and I do have to decide whether or not I am going to implement and support features I do not use myself. This has more impact than your specific request here.

I did not come to a conclusion yet but currently, I am preferring the approach of kindly asking you for a fork and implement and maintain it yourself and keep my repo aligned with my personal use-cases so that I am able to detect regression issues instantly during my daily use.

Background: A system like lazyblorg is hard to 100% unit test. I had to shift from function-based unit-tests (only) to an approach where I combine a simpler set of function-based unit-tests with very high level unit tests. Those tests basically consist of Org-mode input files and a comparison to their HTML result files.

What do you think of my thoughts?

**Comment by nickgarber** [comment]
Hi @novoid, I'll be happy to fork and maintain separately.

I'm grateful for lazyblorg and so don't want to interfere with it's motivations. I'll try to make it simple and desirable to pull changes from.

Thank you for relaying your thoughts in such a considered and eloquent way.

**Comment by nickgarber** [comment]
You can see the fork at https://gitlab.com/nickgarber/lazyblorg (I'm curious about GitLab lately)

**Comment by novoid** [comment]
Thanks Nick for your kind feedback!

**Comment by xeruf** [comment]
@nickgarber it seems like you did not fulfill your ideas? I am starting to use lazyblorg and are interested in these possibilities as well :)
