### ISSUE TITLE
lazyblorg for technical reports and literate programming

### ISSUE THREAD

**Issue by riversdark** [novoid/lazyblorg#59]
Hi, thanks for making lazyblorg :) I'm just getting started with it and I'm wondering if it's suited for my purpose, specifically for writing technical posts and for literate programming. The things I have in mind include:

- running code and insert the results, including graphical results. I see that images are supported through some specific methods, but are they suited for the output graphs for statistical analysis? From what I understand lazyblorg keeps the images permanently in some dedicated folders, but the output graphs are temporary files generated when the code is run, I'm not sure whether lazyblorg can find and properly deal with them. 

- Also I noticed that when the code blocks are named, lazyblorg simply insert the block names into the post as normal text, which doesn't look very good. I would prefer to be able to hide them, or at least to deal with them differently so they don't interrupt the flow of the article.

- syntax highlighting for code snippets. I analyse data with Python, specifically the Emacs-jupyter packages, which has a different header (jupyter-python rather than python), I'm not sure whether lazyblorg can properly syntax highlight the code blocks.

- latex mixed in the prose. I see that latex blocks are supported, how about latex code outside the blocks?

Thanks! I like Lazyblorg's simple but aesthetically pleasing look, but I think your use cases are quite different from mine so I'm not sure it will suit my need.

**Comment by novoid** [comment]
Hi @riversdark,

Simple answer: I only coded what I need so far. And your use-cases differ from mine. Therefore, all four use-cases currently do not work.

Image results: you can currently insert babel blocks. There is no syntax highlighting and I won't implement it. You can define output file names on a defined path which is indexed by lazyblorg. You can then add a lazyblorg-style image reference with captions, scaling, alt text, original size link and all.

LaTeX: not my use-case, sorry. You can try if my fall-back to pandoc kicks in and renders LaTeX code properly. 

I'll close this issue for now but you may keep writing me here if there is anything you think I might be able to help.
