### ISSUE TITLE
Can't cope with timestamp without time

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#77]
lazyblorg.py complains about the following created timestamp. Adding a time to it fixes it, but I don't want to do that for all my already written articles...
```sh
:PROPERTIES:
:ID:       compromising
:CREATED: [2022-08-31 Wed]
:MODIFIED: [2022-08-31 Wed]
:END:
```

```
DEBUG    2022-09-03 23:36:57,312 OrgParser: ------------------------------- drawer_prop
DEBUG    2022-09-03 23:36:57,312 OrgParser: drawer_prop ###### line: ":CREATED: [2022-08-31 Wed]"
ERROR    2022-09-03 23:36:57,312 'NoneType' object has no attribute 'group' ... in line ":CREATED: [2022-08-31 Wed]"
ERROR    2022-09-03 23:36:57,312 Probably malformed time-stamp entry.
Traceback (most recent call last):
  File "/home/janek/data/1-projects/1-personal/lazyblorg/./lazyblorg.py", line 595, in <module>
    generate, marked_for_feed, increment_version, stats_parsed_org_files, stats_parsed_org_lines = lazyblorg.determine_changes()
  File "/home/janek/data/1-projects/1-personal/lazyblorg/./lazyblorg.py", line 80, in determine_changes
    file_blog_data, new_org_lines = self._parse_orgmode_file(
  File "/home/janek/data/1-projects/1-personal/lazyblorg/./lazyblorg.py", line 204, in _parse_orgmode_file
    return parser.parse_orgmode_file()
  File "/home/janek/data/1-projects/1-personal/lazyblorg/lib/orgparser.py", line 851, in parse_orgmode_file
    self.CREATED_REGEX.match(line).group(self.CREATED_TIMESTAMP_IDX)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by novoid** [comment]
Yes, this is an assumption that got defined in early stage of this project. I'm sorry but this won't change.

If it helps you, those timestamps get created in an automatic way when using the `org-expiry` package like I do in my configuration: https://github.com/novoid/dot-emacs/blob/master/config.org

You might search&replace "Mon]" -> "Mon 00:00]" for all days of the week as a migration path of existing headings.

**Comment by xeruf** [comment]
Is there any constraint why this can't be optional, or are you simply not willing to implement it?
In case of the latter I could look into it.

**Comment by novoid** [comment]
I really don't know what chain reaction this would cause.

Since this is not part of my set of requirements and lazyblorg is basically only used by myself so far, I am not willing to implement it. If you achieve a pull request that has no side-effects, I'm happy to apply it.

**Comment by novoid** [comment]
FYI: The pull request by @xeruf did solve this issue and he wrote that he tested it in his setup without an issue.
