### ISSUE TITLE
Use relative links

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#78]
The links to the CSS & co, even on the homepage, start with `/` which means you can't easily have a look at the HTML locally by opening the files, you need to spin up a webserver.

**Comment by novoid** [comment]
I think I remember some issues with relative links and the validator (or similar) which caused me to switch from relative to absolute links.

I'm sorry, this won't change.

**Comment by xeruf** [comment]
okay, I could partially fix this by removing the BASE_URL in the config :)

**Comment by novoid** [comment]
> okay, I could partially fix this by removing the BASE_URL in the config :)

Is there some learning I should add to the README for others in your situation? Maybe you could provide a few lines explaining your approach? Thanks @xeruf

**Comment by xeruf** [comment]
Sure!

If your site resides on the root of your domain, you can easily compile it in a domain-independent way by removing the BASE_URL prefix for the CSS and LOGO path, for example:
```ini
CSS_URL = '/public_voit.css'
BLOG_LOGO = '/images/public-voit_logo.svg'
```
Then you can use for example [caddy](https://caddyserver.com/docs/quick-starts/static-files) to preview the blog locally by issuing `sudo caddy file-server` from the compilation directory (`/tmp/lazyblorg/blog` by default).

**Comment by novoid** [comment]
Thanks, I just linked it in the README.
