### ISSUE TITLE
Missing simple markup like italics?

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#79]
I have some italicized text which I can see being parsed in the log, but it stays wrapped in slashes and unformatted :/
```sh
DEBUG    2022-09-03 23:34:12,919 OrgParser: entry_content ###### line: "/That/ is why I don't want to eat as much meat,"
```

**Comment by novoid** [comment]
This is a duplicate of https://github.com/novoid/lazyblorg/issues/25
