### ISSUE TITLE
Improve styling based on a minimalist framework

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#83]
I have done some research, which is now available on my WIP-instance of lazyblorg: https://blog.jfischer.org/2020/04/04/ui-frameworks/

https://selekkt.dk/skelet/v3/ looks solid and the author has been responsive in issues.
One of the great improvements would be automatic light/dark mode according to user preferences.

I would investigate this further, as I would like to make my blog look good, are you interested in receiving an upstream contribution about this?

**Comment by novoid** [comment]
Unfortunately, your blog does seem to be down from my point of view: "The site could be temporarily unavailable or too busy. Try again in a few moments." I've had this also on the weekend.

ad upstream contribution: difficult. I understand your goal and I do think it's really worth to take a look here. On the other hand, I don't want to have something in my setup I don't understand completely. So it depends on the complexity and the migration effort as I don't want to invest too much time on this. FYI: there are many ideas labeld as "priohigh" I'd consider more important than that. And even for them I don't have much time these days. Unfortunately, for me lazyblorg is working somehow enough. So the pain is too low to invest my spare time for the moment.

However, I encourage you to fork the project. I'm happy to link your project in my README and you can continue with your approaches without me being the downer so many times. ;-)

**Comment by xeruf** [comment]
I see your points, and I will try to contain the changes well, as I always try to hold projects together. Let's see.

The blog is currently IPv6-only, that might be it.

**Comment by novoid** [comment]
> The blog is currently IPv6-only, that might be it.

I did not test IPv6 but somehow assumed that I'm able to access it with my current setup (Xubuntu 22.04 LTS + recent Firefox). I'm puzzled why I can't access your page. :-(

**Comment by xeruf** [comment]
You have to check whether you have a non-local IPv6 address for example in `ip -br a`
You can also use https://blog.jfischer.org:444 for IPv4 access now.

**Comment by novoid** [comment]
Still off-topic:

> You have to check whether you have a non-local IPv6 address for example in `ip -br a` You can also use https://blog.jfischer.org:444 for IPv4 access now.

Thanks. Now I can read your blog. I do think I'm rather IPv6 ignorant so far. I guess I'd need to add IPv6 settings to my OpenWRT infrastructure at home. My ISP most probably does support it but so far I do not have a single argument why I should bother. (Don't be offended - I do have an idea why you do prefer IPv6 as many friends of mine do so as well while fighting windmills.)

**Comment by xeruf** [comment]
There is a simple reason I prefer IPv6: IPv4-adresses cost money, typically 2-3 bucks per address.
IPv6-adresses are free, abundant, and often even slightly faster ;) 

The global level of IPv6-ignorance is crazy. Github and Docker Hub are just two common platforms still on IPv4-only, and I have no idea why. It's not like you have to do anything to adopt IPv6 other than update your config to add an address. It has been clear for over two decades (longer than I have been alive!) that IPv4 can not serve us well in the long term...

**Comment by xeruf** [comment]
Back to topic: For now I dirtily merged your current stylesheet with https://gongzhitaao.org/orgcss/ on my site https://barelybuggy.blog. There is some optimising to do, but overall I immediately found it more pleasing to the eyes.
For me dark mode is a must though, so not sure if that will be the way to go.

**Comment by novoid** [comment]
> Back to topic: For now I dirtily merged your current stylesheet with https://gongzhitaao.org/orgcss/ on my site https://barelybuggy.blog. There is some optimising to do, but overall I immediately found it more pleasing to the eyes. For me dark mode is a must though, so not sure if that will be the way to go.

From my point of view, your web page layout looks broken:

![image](https://github.com/novoid/lazyblorg/assets/727493/bd5c5a58-a214-4ed3-ad6e-ff662be9f247)

Even when I activate JS (NoScript), it doesn't look different.

Firefox 113.0 (64-bit) here, Xubuntu LTS.

**Comment by xeruf** [comment]
yes, it was broken, fixed it now
some things I would definitely recommend adjusting:
- hover state for links
- line-height (I use 1.4)
- body max-width (I use 95%)
I also think that the blue I have fits much nicer with the pleasant yellow background :)

**Comment by novoid** [comment]
As I wrote above: drop me a line when you reached a state where your design could be shared and I'll add a link to your page. I guess anybody is able to get your CSS file to reproduce your styling. You might also write a short blog article explaining how it can be done and this would be the perfect entry point for my link to you.
