### ISSUE TITLE
Replace shell scripts with Makefile?

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#87]
Whenever I see a bunch of shell scripts to build and test, I think that it is time for a Makefile.
It reduces clutter, eases invocation (even somewhat cross-platform) and can handle dependencies.

Would you be open for a contribution taking care of that?

**Comment by novoid** [comment]
Hi @xeruf,

I've been using Makefiles for LaTeX for decades. I won't say that I'm a Makefile pro. However, a switch to something different than Shellscript should be something more modern than Makefiles which is - in my opinion - in its final days (just as shell scripts you may argue here). Makefiles are limited to Unix-like OS (with probably viable exceptions for Windows WSL I guess) and they do have a syntax that shows its age (mandatory tabs, really?).

I don't know what technology would compensate those disadvantages. Maybe there is something from the Python community? This would not add yet another outdated technology to the project.

For me, the current shellscripts are working fine. They're ugly, yes. However, according to "DISCLAIMER: This is a personal project" and its content from [the README](https://github.com/novoid/lazyblorg), I don't see much gain in investing work here just to make it work like it works now.

**Lazyblorg will never be a popular project** used by many people and **I don't want to invest work** to change that. I really love its features and the overall concept but the lazyblorg implementation sucks on so many levels (as you rightfully stated multiple times) that **a completely rewrite would be necessary** to move it to a scalable project for the masses.

It's cool that you do show interest. Fork it, do whatever you like according to its license. I'm very happy to link your fork in my README if you reach out to me when you've got to a certain degree of increased maturity. :+1:
