### ISSUE TITLE
Add venv info

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#94]
One of the latest commits added a requirement for a venv for running the tests, without any elaboration on how to use it :/

**Comment by novoid** [comment]
Hm, I thought that venv is a common pattern in the Python3 world and I don't have to explain on how to create a venv and install the requirements for that project within that venv ...

What would you expect to read?

**Comment by novoid** [comment]
Good point ;-)

Well, I think this is resolved by making it optional.
