### ISSUE TITLE
Ability to Schedule posts in the future

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#97]
Currently, if the published/created timestamp is in the future, lazyblorg seems to publish the post regardless.
I think this guy implemented scheduling posts in his file: https://endlessparentheses.com/how-i-blog-one-year-of-posts-in-a-single-org-file.html

While we are at it, it would be good to document the point of all the various timestamps (created, published, in the logbook note; `CLOSED` seems to be ignored). To me it seems only one is ever used, why require and parse all the other ones?

**Comment by novoid** [comment]
Hi,

Unfortunately, this is not possible without investing a large amount of effort throughout all data structures and so forth. Just imagine you're using cross-links between articles where one side is published and the other one isn't. So lazyblorg would need to track each and every link, meta-data, counter, ... separately for published and unpublished articles.

This is the reason why I stick to DONE as a keyword. As long as you don't set it to DONE, it is ignored (and any link from another article to that unpublished one provokes a warning or an error).
