### ISSUE TITLE
Limit tag cloud size

### ISSUE THREAD

**Issue by xeruf** [novoid/lazyblorg#99]
Especially when looking at your own blog on a smaller screen, the tag cloud tends to push off the actual content.
I would suggest dropping the least used tags from it, maybe through a config variable that sets the count of top tags to include in the cloud. And maybe find a way to arrange them more densely.

Setting `max-height: 30vh` and `overflow: hidden` also seems a decent solution.

**Comment by novoid** [comment]
For the longest time, I didn't feature the tag cloud on the landing page at all.

You might want to remove it from the template and rely on the URL/tags/ page alone.

You may add more tags to the `config.py`:

```
## list of strings: tags to ignore when generating misc things:
IGNORE_FOR_TOP_TAGS = ['suderei', 'personally']
IGNORE_FOR_TAG_CLOUD = ['suderei', 'personally', 'hardware', 'software']
```

**Comment by novoid** [comment]
As a side-note: in https://karl-voit.at/2022/01/29/How-to-Use-Tags/ I explain why I do think that having as few tags as possible (and as many as necessary) is a good goal.

**Comment by xeruf** [comment]
Will have a look at the article!

I like the tag cloud on the start page, adds some dynamic.

> You may add more tags to the config.py:

This is quite the opposite of what I want, as this is supposedly for very common tags.
I want the program to filter out tags that are only used 1-2 times and thus likely not relevant.
